import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../components/index'
import HomePage from '../components/Features/Home'
import { Product } from '../type/type'
export const getStaticProps = async () => {
  const res = await fetch("https://6336ba535327df4c43c81ae6.mockapi.io/users");
  const products = await res.json();

  return {
    props: { products },
  };
};
const Home: NextPage<{products: Product[]}> = ({products}) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <HomePage products={products}/>
    </>
  )
}

export default Home
