import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/index";
import "owl.carousel/dist/assets/owl.carousel.css";
import "owl.carousel/dist/assets/owl.theme.default.css";
import dynamic from "next/dynamic";
import "animate.css";
import ServiceItem from "../components/modules/ServiceItem";
import ProductItem from "../components/modules/ProductItem";
import { services, slider } from "../data/data";
import { Product } from "../type/type";
import SlideItem from "../components/modules/SlideItem";
export const getStaticProps = async () => {
  const res = await fetch("https://6336ba535327df4c43c81ae6.mockapi.io/users");
  const products = await res.json();

  return {
    props: { products },
  };
};

const OwlCarousel = dynamic(() => import("react-owl-carousel"), {
  ssr: false,
});

const Home: NextPage<{ products: Product[] }> = ({ products }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="page-home">
        <section className="section-intro">
          <OwlCarousel className="owl-theme" loop margin={10} items={1}>
              {slider.map(slide =>(
                <SlideItem key={slide.id} slide={slide}   />
              ))}
          </OwlCarousel>
        </section>
        <section className="section-service">
          <div className="container">
            <h6 className="section-sub-title">What We Do</h6>
            <h2 className="section-title">Unlimited Possibilities</h2>
            <ul className="service-list flex">
              {services.map((service, index) => (
                <ServiceItem service={service} key={index} />
              ))}
            </ul>
          </div>
        </section>
        <section className="section-popular">
          <div className="container">
            <h6 className="section-sub-title">The Best Choice</h6>
            <h2 className="section-title">Popular Courses</h2>
            <ul className="product-list">
              {products.map((product, index) => {
                return <ProductItem product={product} key={index} />;
              })}
            </ul>
          </div>
        </section>
      </div>
    </>
  );
};

export default Home;
